version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.development.local
    ports:
      - "3000:3000"
    depends_on:
      - mssql
    networks:
      - my_network
    volumes:
      - .:/app
      - /app/node_modules

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    networks:
      - my_network
    volumes:
      - mssql_data:/var/opt/mssql

networks:
  my_network:
    driver: bridge

volumes:
  mssql_data:
