FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate

ENV PRISMA_FORCE_DEV_ENV=true

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate dev --create-only --name init && npm run start:dev"]
