version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - mssql
    networks:
      - backend_network
    volumes:
      - /app/node_modules
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU4-ubuntu-20.04
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  mssql_data:
